name: AdminPanel 
services:
  backend:
    #image: adminpanel.web
    container_name: AdminPanel.API
    build:
      context: ./backend
      dockerfile: AdminPanel.Web/Dockerfile  
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Database=Host=postgres;Port=5432;Database=AdminPanel;Username=postgres;Password=postgres
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  frontend:
    container_name: AdminPanel.UI
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  postgres:
    image: postgres:latest
    container_name: AdminPanel.Db
    environment:
      POSTGRES_DB: "AdminPanel"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d AdminPanel"]
      interval: 5s
      timeout: 5s
      retries: 5