// <auto-generated />
using System;
using AdminPanel.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdminPanel.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250618091556_AddPaymentAndRate")]
    partial class AddPaymentAndRate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdminPanel.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b4b4145-6122-4d99-9d7b-e669112618fe"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@mirra.dev",
                            Password = "$2a$11$..1tQa8qz03JlNsIgHn9ZOc2/iUEM5Y1RYCRbxcm0Y.B5wLV0ZCpO"
                        });
                });

            modelBuilder.Entity("AdminPanel.Domain.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Client");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3c4ea0e-3c29-4ffe-82a8-8e72857035f3"),
                            Balance = 500000.11m,
                            CreatedAt = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ivan.petrov@example.com",
                            Name = "Иван Петров"
                        },
                        new
                        {
                            Id = new Guid("f33b8c2e-9335-419a-a1ca-85d6eb5f5c89"),
                            Balance = 100000m,
                            CreatedAt = new DateTime(2023, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "contact@globalinvest.ru",
                            Name = "ООО 'Глобал Инвест'",
                            UpdatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("751150d4-8e8e-466f-ac7d-bea47981281e"),
                            Balance = 200000m,
                            CreatedAt = new DateTime(2021, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "contact@rogakopyta.ru",
                            Name = "ООО 'Рога и Копыта'",
                            UpdatedAt = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AdminPanel.Domain.Clients.ClientTag", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tag")
                        .HasColumnType("integer");

                    b.HasKey("ClientId", "Tag");

                    b.ToTable("ClientTag");

                    b.HasData(
                        new
                        {
                            ClientId = new Guid("751150d4-8e8e-466f-ac7d-bea47981281e"),
                            Tag = 3
                        },
                        new
                        {
                            ClientId = new Guid("751150d4-8e8e-466f-ac7d-bea47981281e"),
                            Tag = 2
                        },
                        new
                        {
                            ClientId = new Guid("751150d4-8e8e-466f-ac7d-bea47981281e"),
                            Tag = 1
                        },
                        new
                        {
                            ClientId = new Guid("751150d4-8e8e-466f-ac7d-bea47981281e"),
                            Tag = 6
                        },
                        new
                        {
                            ClientId = new Guid("751150d4-8e8e-466f-ac7d-bea47981281e"),
                            Tag = 7
                        },
                        new
                        {
                            ClientId = new Guid("f33b8c2e-9335-419a-a1ca-85d6eb5f5c89"),
                            Tag = 4
                        },
                        new
                        {
                            ClientId = new Guid("f33b8c2e-9335-419a-a1ca-85d6eb5f5c89"),
                            Tag = 8
                        },
                        new
                        {
                            ClientId = new Guid("f33b8c2e-9335-419a-a1ca-85d6eb5f5c89"),
                            Tag = 5
                        },
                        new
                        {
                            ClientId = new Guid("e3c4ea0e-3c29-4ffe-82a8-8e72857035f3"),
                            Tag = 3
                        },
                        new
                        {
                            ClientId = new Guid("e3c4ea0e-3c29-4ffe-82a8-8e72857035f3"),
                            Tag = 7
                        },
                        new
                        {
                            ClientId = new Guid("e3c4ea0e-3c29-4ffe-82a8-8e72857035f3"),
                            Tag = 1
                        });
                });

            modelBuilder.Entity("AdminPanel.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RateId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("AdminPanel.Domain.Rates.Rate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Rate");

                    b.HasData(
                        new
                        {
                            Id = new Guid("af9ee87c-c49c-4935-95af-fdbf850bc455"),
                            CreatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 201m
                        },
                        new
                        {
                            Id = new Guid("aecae947-96fa-4891-8fc1-6cdef3c8b8bf"),
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 179m
                        },
                        new
                        {
                            Id = new Guid("1224c302-d8ce-4bf6-bf0f-c8fdce929f67"),
                            CreatedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 113m
                        },
                        new
                        {
                            Id = new Guid("376a4fb5-9a56-458f-b6dc-82f9879abf1e"),
                            CreatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 120m
                        },
                        new
                        {
                            Id = new Guid("c96fd987-8f25-4cd3-af6e-45e9fa7f4c0c"),
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 140m
                        },
                        new
                        {
                            Id = new Guid("1c418e7a-9d11-4f65-bca1-f193c1eb5a6c"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 109m
                        },
                        new
                        {
                            Id = new Guid("ad092827-b3d3-4971-b1a0-0cb7e93c733f"),
                            CreatedAt = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 51m
                        },
                        new
                        {
                            Id = new Guid("f704312b-9da0-48ee-bd0b-a90a4d1c7644"),
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 94m
                        },
                        new
                        {
                            Id = new Guid("000fe0dc-5c77-4f7d-a97a-337d54bf34fa"),
                            CreatedAt = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 86m
                        },
                        new
                        {
                            Id = new Guid("d7a8b7ea-d0ca-468a-8d1c-ff421eb15463"),
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 100m
                        });
                });

            modelBuilder.Entity("AdminPanel.Domain.RefreshTokens.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("AdminPanel.Domain.Clients.ClientTag", b =>
                {
                    b.HasOne("AdminPanel.Domain.Clients.Client", null)
                        .WithMany("Tags")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminPanel.Domain.Payments.Payment", b =>
                {
                    b.HasOne("AdminPanel.Domain.Clients.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminPanel.Domain.Rates.Rate", "Rate")
                        .WithMany()
                        .HasForeignKey("RateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Rate");
                });

            modelBuilder.Entity("AdminPanel.Domain.RefreshTokens.RefreshToken", b =>
                {
                    b.HasOne("AdminPanel.Domain.Accounts.Account", null)
                        .WithOne()
                        .HasForeignKey("AdminPanel.Domain.RefreshTokens.RefreshToken", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminPanel.Domain.Clients.Client", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
